const FallbackThree=(()=>{class Obj{constructor(){this.position={x:0,y:0,z:0,set(x,y,z){this.x=x;this.y=y;this.z=z}};this.rotation={x:0,y:0,z:0};this.userData={}}add(o){this.children??=[];this.children.push(o)}remove(o){this.children=this.children?.filter(x=>x!==o)||[]}traverse(fn){(this.children||[]).forEach(fn)} }class Scene extends Obj{constructor(){super();this.children=[]}set background(v){this.bg=v}}class Mesh extends Obj{constructor(g,m){super();this.geometry=g;this.material=m}}class Renderer{constructor(){this.domElement=document.createElement('canvas')}setPixelRatio(){}setSize(w,h){this.domElement.width=w;this.domElement.height=h;this.domElement.style.width='100%';this.domElement.style.height='100%'}render(){const c=this.domElement.getContext('2d');if(c){c.fillStyle='#1b2030';c.fillRect(0,0,this.domElement.width,this.domElement.height);c.fillStyle='#d8ff55';c.font='14px monospace';c.fillText('ARCADE MODE READY',24,34)}}}class Camera{constructor(){this.position=new Obj()}lookAt(){}}class Clock{constructor(){this.started=performance.now()}getElapsedTime(){return (performance.now()-this.started)/1000}}const Empty=class{};return{Scene,Mesh,WebGLRenderer:Renderer,PerspectiveCamera:Camera,Clock,Vector3:class{},Color:class{},MeshStandardMaterial:Empty,BoxGeometry:Empty,SphereGeometry:Empty,CylinderGeometry:Empty,HemisphereLight:Empty,DirectionalLight:Empty,Mesh}})();
FallbackThree.HemisphereLight=class extends FallbackThree.Mesh{constructor(){super(null,null)}};FallbackThree.DirectionalLight=FallbackThree.HemisphereLight;
const THREE=window.THREE||FallbackThree;
const mode=document.body.dataset.game, host=document.querySelector('.three-stage'), panel=document.querySelector('#game-panel'), scoreEl=document.querySelector('#score'), timeEl=document.querySelector('#time'), start=document.querySelector('[data-key="start"]');
let score=0,time=60,playing=false,timer,runnerState=null,shooterState=null;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(55,host.clientWidth/host.clientHeight,.1,100);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);host.appendChild(renderer.domElement);
scene.background=new THREE.Color(mode==='shooter'?0x172126:mode==='runner'?0x70bfd1:0x29234e);camera.position.set(7,5.5,9);
scene.add(new THREE.HemisphereLight(0xffffff,0x27313b,2.5));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(-4,8,5);scene.add(sun);
const material=c=>new THREE.MeshStandardMaterial({color:c,roughness:.7}),ground=material(mode==='shooter'?0x293d39:mode==='runner'?0x347454:0x342852),lime=material(0xd8ff55),coral=material(0xff715f),cyan=material(0x65e5ff),dark=material(0x22212c);
function add(g,m,x,y,z){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;scene.add(o);return o}
add(new THREE.BoxGeometry(18,.5,18),ground,0,-.35,0);
if(mode==='2048'){for(let x=-4;x<5;x+=2)for(let z=-2;z<4;z+=2)add(new THREE.BoxGeometry(1.7,1.7,1.7),[lime,coral,cyan][((x+z+10)/2)%3|0],x,.55,z);add(new THREE.BoxGeometry(1.7,4,1.7),lime,3,1.65,-2)}
if(mode==='runner'){for(let i=0;i<9;i++)add(new THREE.BoxGeometry(2.2,.45,2.2),i%2?lime:coral,Math.sin(i*.8)*4,i*.3,Math.cos(i*.8)*2-2);add(new THREE.BoxGeometry(1,2.4,1),cyan,0,1.2,1);add(new THREE.SphereGeometry(.55,16,12),coral,0,2.8,1)}
if(mode==='shooter'){for(let i=-2;i<3;i++)add(new THREE.BoxGeometry(.4,3,8),dark,i*3,1.15,-2);add(new THREE.BoxGeometry(8,.3,.3),lime,0,2.8,-5);for(let i=0;i<4;i++){const t=add(new THREE.CylinderGeometry(1,.75,.25,20),i%2?coral:lime,-4+i*2,1.5,-4);t.rotation.x=Math.PI/2}}
const target=new THREE.Vector3(0,1,0),clock=new THREE.Clock();
function animate(){requestAnimationFrame(animate);const t=clock.getElapsedTime();camera.position.x=7+Math.sin(t*.18)*.5;camera.lookAt(target);if(runnerState&&playing)updateRunner(t);if(shooterState&&playing)updateShooter(t);renderer.render(scene,camera)}animate();
addEventListener('resize',()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)});
function updateHud(){scoreEl.textContent=score;timeEl.textContent=time}
function startGame(){playing=true;score=0;time=60;updateHud();start.textContent='RESTART GAME ↻';clearInterval(timer);timer=setInterval(()=>{time--;updateHud();if(time<=0)endGame()},1000);if(mode==='2048')new2048();if(mode==='runner')newRunner();if(mode==='shooter')newShooter()}
function endGame(){clearInterval(timer);playing=false;panel.innerHTML='<div class="question">TIME UP · FINAL SCORE '+score+'</div>'}
start.addEventListener('click',startGame);
addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.repeat){e.preventDefault();startGame()}});

function new2048(){let board=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];addTile();addTile();renderBoard();function addTile(){const empty=board.map((v,i)=>v?null:i).filter(i=>i!==null);if(empty.length)board[empty[Math.floor(Math.random()*empty.length)]]=Math.random()<.9?2:4}function slide(line){const values=line.filter(Boolean),out=[];for(let i=0;i<values.length;i++){if(values[i]===values[i+1]){out.push(values[i]*2);score+=values[i]*2;i++}else out.push(values[i])}while(out.length<4)out.push(0);return out}function move(dir){if(!playing)return;let grid=Array.from({length:4},(_,r)=>board.slice(r*4,r*4+4));if(dir==='ArrowUp'||dir==='ArrowDown'){grid=grid[0].map((_,c)=>grid.map(row=>row[c]));if(dir==='ArrowDown')grid=grid.map(row=>row.reverse())}else if(dir==='ArrowRight')grid=grid.map(row=>row.reverse());let moved=grid.map(row=>slide(row));if(dir==='ArrowDown'||dir==='ArrowRight')moved.forEach(row=>row.reverse());if(dir==='ArrowUp'||dir==='ArrowDown')moved=moved[0].map((_,c)=>moved.map(row=>row[c]));const next=moved.flat();if(next.some((v,i)=>v!==board[i])){board=next;addTile();renderBoard();updateHud()}}function renderBoard(){panel.innerHTML='<div class="board">'+board.map(v=>'<div class="board-cell" data-value="'+v+'">'+(v||'')+'</div>').join('')}</div>'}addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();move(e.key)}});let startX=0;panel.addEventListener('touchstart',e=>startX=e.touches[0].clientX,{passive:true});panel.addEventListener('touchend',e=>{const d=e.changedTouches[0].clientX-startX;move(d>20?'ArrowRight':d<-20?'ArrowLeft':'ArrowUp')},{passive:true})}
function question(){const a=2+Math.floor(Math.random()*9),b=2+Math.floor(Math.random()*9);return{a,b,answer:a+b}}

function newRunner(){const player=add(new THREE.BoxGeometry(.65,1,.65),cyan,0,.7,3);runnerState={player,lane:1,targetLane:1,jump:0,question:question(),gates:[],lastGate:0};renderRunnerQuestion();document.onkeydown=e=>{if(!playing)return;if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')runnerState.targetLane=Math.max(0,runnerState.targetLane-1);if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')runnerState.targetLane=Math.min(2,runnerState.targetLane+1);if((e.key==='ArrowUp'||e.key===' ')&&runnerState.jump===0)runnerState.jump=.01};}
function renderRunnerQuestion(){const q=runnerState.question,vals=[q.answer,q.answer+2,q.answer-1].sort(()=>Math.random()-.5);panel.innerHTML='<div class="question">RUN THROUGH: '+q.a+' + '+q.b+' = ?</div><div class="answers">'+vals.map(v=>'<button class="answer" data-answer="'+v+'">'+v+'</button>').join('')+'</div>';panel.querySelectorAll('.answer').forEach(btn=>btn.onclick=()=>pickRunner(+btn.dataset.answer))}
function pickRunner(v){if(!playing)return;if(v===runnerState.question.answer){score+=10;runnerState.question=question();renderRunnerQuestion()}else{score=Math.max(0,score-3);updateHud()}}
function updateRunner(t){const r=runnerState;r.lane+=(r.targetLane-r.lane)*.12;r.player.position.x=(r.lane-1)*2.1;r.player.position.y=r.jump>0?1.7:0.7;if(r.jump>0){r.jump+=.055;if(r.jump>Math.PI)r.jump=0;r.player.position.y=.7+Math.sin(r.jump)*1.3}if(t-r.lastGate>.9){const g=add(new THREE.BoxGeometry(1.4,.5,.5),Math.random()>.5?coral:lime,(Math.floor(Math.random()*3)-1)*2.1,.45,-7);g.userData.lane=Math.round((g.position.x+2.1)/2.1);r.gates.push(g);r.lastGate=t}r.gates.forEach(g=>{g.position.z+=.12;if(g.position.z>3.5){scene.remove(g);return}if(g.position.z>2.6&&g.position.z<3.3&&g.userData.lane===Math.round(r.lane)&&r.jump===0){score=Math.max(0,score-2);g.position.z=4} });updateHud()}

function newShooter(){shooterState={question:question(),targets:[]};renderShooter();document.onkeydown=e=>{if(e.key==='r'&&playing)newShooter()}}
function renderShooter(){const s=shooterState,q=s.question;panel.innerHTML='<div class="question">FIRE AT: '+q.a+' + '+q.b+' = ?</div>';for(let i=0;i<4;i++){const b=document.createElement('button');b.className='ops-target';b.textContent=i===0?q.answer:q.answer+i+2;b.style.left=(8+Math.random()*78)+'%';b.style.top=(15+Math.random()*70)+'%';b.onclick=()=>{if(!playing)return;if(+b.textContent===q.answer){score+=10;b.classList.add('hit');setTimeout(newShooter,130)}else{score=Math.max(0,score-2);b.classList.add('miss');setTimeout(()=>b.classList.remove('miss'),180)}updateHud()};panel.appendChild(b);s.targets.push(b)}}
function updateShooter(t){if(!panel.querySelector('.ops-target'))return;panel.querySelectorAll('.ops-target').forEach((b,i)=>{b.style.transform='translateY('+Math.sin(t*2+i)*7+'px)'})}
